frequency: 5.0
delay: 0.0  # Simulated GPS needs no start-up time
# delay: 90.0 # Real GPS start-up time

# Initial configuration
magnetic_declination_radians: 0.0
yaw_offset: 1.5707963 # pi/2 rad since 0 yaw == North
zero_altitude: true

# Publishing data
publish_filtered_gps: true
broadcast_cartesian_transform: true # NOTE: publishes transform (frame sepcified from input odometry) --> UTM
broadcast_cartesian_transform_as_parent_frame: true

# Misc
use_odometry_yaw: false
wait_for_datum: false
transform_timeout: 0
