obstacle_range: 5.5
raytrace_range: 6.0
max_obstacle_height: 1.0
min_obstacle_height: 0.5

footprint: [[-0.734, -0.582], [-0.734, 0.582], [0.734, 0.582], [0.734, -0.582]]
inflation_radius: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: caffeine/base_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
