subscibe_depth: false
subscribe_scan: false
subscribe_stereo: true
frame_id: /base_link
map_frame_id: /map
# odom_frame_id: /odom
queue_size: 30
grid_size: 100
use_action_for_goal: true
ignore_variance: true
tf_delay: 0.025
# gen_scan_max_depth: 4.0

# Deals with the "large angular variance error". Loop closure would essentially fail and map will be useless
# Hard coded solution from rtab creator. Tune later

odom_tf_linear_variance: 0.0001    # adjust depending on real odom error
odom_tf_angular_variance: 0.0001   # adjust depending on real odom error

Vis:
  MinInliers: 12

RGBD:
  CreateOccupancyGrid: true
